### ISSUE TITLE
Repeated poster of ENFJ and missing poster of ENFP

### ISSUE THREAD

**Issue by Aparna106** [AureliaSindhu/Toastology#1]
In the toast.html, poster carasoul, in the "st" classes, div 4 and div 9 are of ENFJ (broccoli and hummus) and the ENFP poster (Blueberry and cream cheese) is missing. Love the test btw, very creative.
![toastology bug](https://github.com/AureliaSindhu/Toastology/assets/78996086/5369f3e0-0085-4588-867b-93d52cddd38e)

**Comment by AureliaSindhu** [comment]
Got it fixed, thank you so much!!
